### Analisi movimenti per più alto numero di opere

In [ ]:
import pandas as pd
# Carica il file CSV
file_path = 'dataset_wikidata.csv'
df = pd.read_csv(file_path)

#regroup naturalism and expressionism
for index, row in df.iterrows():
    if row['movementLabel'] == 'expressionism':
        df.at[index, 'movementLabel'] = 'Expressionism'
        df.at[index, 'movement'] = 'https://www.wikidata.org/wiki/Q80113'
    if row['movementLabel'] == 'naturalism':
        df.at[index, 'movementLabel'] = 'Naturalism'
        df.at[index, 'movement'] = 'https://www.wikidata.org/wiki/Q55995'


# Seleziona le colonne desiderate
df_subset = df[['movementLabel', 'movstart', 'movend', 'inception', 'works']]

# Raggruppa per 'movementLabel' e conta il numero di opere in ciascun gruppo
df_grouped = df_subset.groupby('movementLabel').agg({
    'movstart': 'first',   # Assumi lo stesso valore di 'movstart' per tutto il gruppo
    'movend': 'first',     # Assumi lo stesso valore di 'movend' per tutto il gruppo
    'inception': 'first', # Assumi lo stesso valore di 'inception' per tutto il gruppo
    'works': 'count'       # Conta il numero di opere nel gruppo
}).reset_index()

# Rinomina la colonna di conteggio
df_grouped = df_grouped.rename(columns={'works': 'number_of_works'})

# Ordina il dataframe in base al numero di opere in ordine decrescente
df_sorted = df_grouped.sort_values(by='number_of_works', ascending=False)

# Stampa il dataframe risultante
df_sorted

,movementLabel,movstart,movend,inception,number_of_works
13,Baroque,1590-01-01T00:00:00Z,1750-01-01T00:00:00Z,None,1745
130,Symbolism,None,None,1857-01-01T00:00:00Z,1672
62,Impressionism,None,None,1860-01-01T00:00:00Z,1451
115,Romanticism,1800-01-01T00:00:00Z,1900-01-01T00:00:00Z,None,1246
180,neoclassicism,1760-01-01T00:00:00Z,1830-01-01T00:00:00Z,None,1232
...,...,...,...,...,...
68,Italian Renaissance painting,None,None,None,1
146,abstraction,None,None,None,1
165,genre painting,None,None,None,1
164,genre art,None,None,None,1
101,Potosi School,None,None,None,1

In [ ]:
df_temp = df_sorted.head(20).fillna('empty')

for index, row in df_temp.iterrows():
    if row['movstart'] == 'empty':
        df_temp.at[index, 'movstart'] = row['inception']

for index, row in df_temp.iterrows():    
    if row['movstart'] != 'empty':
        start_year = str(row['movstart']).split('-')[0]
        df_temp.at[index, 'movstart'] = (int(start_year))
    if row['movend'] != 'empty':
        end_year= str(row['movend']).split('-')[0]
        df_temp.at[index, 'movend'] = (int(end_year))

df_time = df_temp.drop(columns=['inception']).drop_duplicates().reset_index()


print(df_time.to_string())

    index                 movementLabel movstart movend  number_of_works
0      13                       Baroque     1590   1750             1745
1     130                     Symbolism     1857  empty             1672
2      62                 Impressionism     1860  empty             1451
3     115                   Romanticism     1800   1900             1246
4     180                 neoclassicism     1760   1830             1232
5     147                  academic art    empty  empty             1134
6     108                       Realism     1848  empty              895
7     192                       realism    empty  empty              844
8     112                        Rococo     1730   1780              765
9     170                     mannerism     1520   1600              672
10     42  Early Netherlandish painting     1420   1560              589
11     94                   Orientalism    empty  empty              583
12     39     Dutch Golden Age painting     1600   1699              570
13     48      Flemish Baroque painting     1585   1700              533
14     60              High Renaissance     1494   1527              503
15    187            post-impressionism     1886   1905              475
16     98              Pont-Aven School     1850  empty              429
17     52            German Renaissance     1500   1600              391
18    102    Pre-Raphaelite Brotherhood     1848  empty              389
19     67           Italian Renaissance     1350   1700              337